test: bats --recursive --print-output-on-failure --abort "${1:-test}" ; echo "Exit code: $?"
#? run tests

generate: bashly generate --env production
#? generate the bash script

shellcheck: shellcheck ssi
#? run shellcheck

completions: bashly add completions_script completions/ssi -fq
#? generate the completions script

readme: sed -E -i "s#releases/download/v[0-9.]+/ssi#releases/download/v$(./ssi --version)/ssi#g" README.md
#? update README version to match ssi --version

checksum: mkdir -p tmp ; sha256sum ssi > tmp/ssi.sha256
#? generate checksum for ssi into tmp/ssi.sha256
