test: bats --recursive --print-output-on-failure --abort "${1:-test}" ; echo "Exit code: $?"
#? run tests

generate: bashly generate --env production
#? generate the bash script

shellcheck: shellcheck ssi
#? run shellcheck