## Build

build:
  echo build: generating production script
  bashly generate --env production --quiet
  op checksum
  op readme
  op completions
#? build everything for release

generate: bashly generate --env production "$@"
#? generate the bash script

## Testing

test: bats --recursive --print-output-on-failure --abort "${1:-test}" ; echo "Exit code: $?"
#? run tests

shellcheck: shellcheck ssi && green PASS
#? run shellcheck

## Extras

completions:
  echo completions: generating script
  bashly add completions_script completions/ssi -fq
#? generate the completions script

readme:
  echo readme: patching version
  sed -E -i "s#releases/download/v[0-9.]+/ssi#releases/download/v$(./ssi --version)/ssi#g" README.md
#? update README version to match ssi --version

checksum:
  echo checksum: generating tmp/ssi.sha256
  sha256sum ssi > tmp/ssi.sha256
  sha256sum -c tmp/ssi.sha256
#? generate checksum for ssi into tmp/ssi.sha256
